import type { Clock01Icon } from "@hugeicons/core-free-icons";
import {
  Alert02Icon,
  BankIcon,
  Book01Icon,
  Briefcase01Icon,
  Building01Icon,
  Camera01Icon,
  Car01Icon,
  Calendar01Icon,
  FavouriteIcon,
  Hotel01Icon,
  JobLinkIcon,
  Restaurant01Icon,
  ShoppingBag01Icon,
  SparklesIcon,
  StethoscopeIcon,
  Store01Icon,
  UserGroup02Icon,
  Wrench01Icon,
} from "@hugeicons/core-free-icons";

import type { BusinessCategory } from "@/db/schema";
import type { Dict } from "@/lib/i18n/config";

// One subcategory level deep, and only where the source hierarchy
// actually nests one (Restaurants, under Food & Drinks) — everything
// else is a flat list. Not wired into any form or filter yet; this
// exists so the tree is on record for when it is.
export type Subcategory = { label: string; children?: string[] };

export const CATEGORY_META: Record<
  BusinessCategory,
  { label: keyof Dict; icon: typeof Clock01Icon; subcategories: Subcategory[] }
> = {
  "food-drinks": {
    label: "Food & Drinks",
    icon: Restaurant01Icon,
    subcategories: [
      {
        label: "Restaurants",
        children: [
          "Fast Food",
          "Fine Dining",
          "Seafood",
          "Pizza",
          "Burgers",
          "Sushi",
          "BBQ",
          "Traditional Food",
          "Vegan",
          "Cafeteria",
        ],
      },
      { label: "Cafés" },
      { label: "Bakeries" },
      { label: "Desserts" },
      { label: "Ice Cream" },
      { label: "Juice Bars" },
      { label: "Coffee Roasters" },
      { label: "Food Trucks" },
      { label: "Home Chefs" },
      { label: "Catering" },
      { label: "Meal Prep" },
    ],
  },
  health: {
    label: "Health",
    icon: StethoscopeIcon,
    subcategories: [
      {
        label: "Doctors",
        children: [
          "General",
          "Dentist",
          "Pediatrician",
          "Dermatologist",
          "Eye",
          "ENT",
          "Gynecology",
          "Cardiology",
        ],
      },
      { label: "Clinics" },
      { label: "Hospitals" },
      { label: "Pharmacies" },
      { label: "Laboratories" },
      { label: "Radiology" },
      { label: "Physiotherapy" },
      { label: "Nutritionists" },
      { label: "Psychologists" },
      { label: "Veterinarians" },
      { label: "Ambulance" },
    ],
  },
  beauty: {
    label: "Beauty",
    icon: SparklesIcon,
    subcategories: [
      { label: "Hair Salons" },
      { label: "Barbers" },
      { label: "Makeup Artists" },
      { label: "Nail Salons" },
      { label: "Spa" },
      { label: "Massage" },
      { label: "Skin Care" },
      { label: "Laser Clinics" },
      { label: "Tattoo" },
      { label: "Bridal Services" },
      { label: "Cosmetics" },
    ],
  },
  creative: {
    label: "Creative",
    icon: Camera01Icon,
    subcategories: [
      { label: "Photography" },
      { label: "Videography" },
      { label: "Drone" },
      { label: "Graphic Design" },
      { label: "Printing" },
      { label: "Branding" },
      { label: "UI/UX" },
      { label: "Web Development" },
      { label: "Mobile Development" },
      { label: "Marketing" },
      { label: "Social Media" },
      { label: "Copywriting" },
      { label: "Animation" },
    ],
  },
  shopping: {
    label: "Shopping",
    icon: ShoppingBag01Icon,
    subcategories: [
      { label: "Grocery" },
      { label: "Supermarkets" },
      { label: "Fashion", children: ["Women", "Men", "Kids", "Shoes"] },
      { label: "Jewelry" },
      { label: "Electronics" },
      { label: "Furniture" },
      { label: "Home Decor" },
      { label: "Books" },
      { label: "Toys" },
      { label: "Sports" },
      { label: "Pet Shops" },
      { label: "Florists" },
      { label: "Gifts" },
    ],
  },
  "home-services": {
    label: "Home Services",
    icon: Wrench01Icon,
    subcategories: [
      { label: "Plumbing" },
      { label: "Electrical" },
      { label: "Cleaning" },
      { label: "Pest Control" },
      { label: "Painting" },
      { label: "Carpentry" },
      { label: "Air Conditioning" },
      { label: "Appliances Repair" },
      { label: "Internet Services" },
      { label: "Security" },
      { label: "Interior Design" },
      { label: "Gardening" },
      { label: "Moving" },
      { label: "Delivery" },
      { label: "Laundry" },
    ],
  },
  automotive: {
    label: "Automotive",
    icon: Car01Icon,
    subcategories: [
      { label: "Mechanics" },
      { label: "Car Wash" },
      { label: "Tires" },
      { label: "Oil Change" },
      { label: "Auto Parts" },
      { label: "Towing" },
      { label: "Car Rental" },
      { label: "Driving Schools" },
      { label: "Car Dealers" },
      { label: "Motorcycle Services" },
      { label: "EV Charging" },
    ],
  },
  education: {
    label: "Education",
    icon: Book01Icon,
    subcategories: [
      { label: "Tutors" },
      { label: "Schools" },
      { label: "Universities" },
      { label: "Training Centers" },
      { label: "Language Centers" },
      { label: "Music Lessons" },
      { label: "Sports Coaches" },
      { label: "Online Courses" },
      { label: "Private Lessons" },
      { label: "Workshops" },
    ],
  },
  tourism: {
    label: "Tourism",
    icon: Hotel01Icon,
    subcategories: [
      { label: "Hotels" },
      { label: "Resorts" },
      { label: "Hostels" },
      { label: "Apartments" },
      { label: "Tour Guides" },
      { label: "Tour Agencies" },
      { label: "Cruises" },
      { label: "Desert Trips" },
      { label: "Boat Trips" },
      { label: "Museums" },
      { label: "Attractions" },
      { label: "Ticket Offices" },
    ],
  },
  "professional-services": {
    label: "Professional Services",
    icon: Briefcase01Icon,
    subcategories: [
      { label: "Lawyers" },
      { label: "Accountants" },
      { label: "Consultants" },
      { label: "Real Estate Agents" },
      { label: "Insurance" },
      { label: "Translators" },
      { label: "HR" },
      { label: "Business Consultants" },
      { label: "Architects" },
      { label: "Engineers" },
    ],
  },
  "real-estate": {
    label: "Real Estate",
    icon: Building01Icon,
    subcategories: [
      { label: "Apartments" },
      { label: "Villas" },
      { label: "Houses" },
      { label: "Land" },
      { label: "Offices" },
      { label: "Shops" },
      { label: "Warehouses" },
      { label: "Hotels" },
      { label: "Property Management" },
      { label: "Brokers" },
    ],
  },
  jobs: {
    label: "Jobs",
    icon: JobLinkIcon,
    subcategories: [
      { label: "Full Time" },
      { label: "Part Time" },
      { label: "Internship" },
      { label: "Freelance" },
      { label: "Remote" },
      { label: "Temporary" },
      { label: "Volunteer" },
    ],
  },
  marketplace: {
    label: "Marketplace",
    icon: Store01Icon,
    subcategories: [
      { label: "Electronics" },
      { label: "Furniture" },
      { label: "Fashion" },
      { label: "Cars" },
      { label: "Motorcycles" },
      { label: "Books" },
      { label: "Pets" },
      { label: "Home Appliances" },
      { label: "Sports" },
      { label: "Gaming" },
      { label: "Free Items" },
    ],
  },
  community: {
    label: "Community",
    icon: UserGroup02Icon,
    subcategories: [
      { label: "Posts" },
      { label: "Questions" },
      { label: "Recommendations" },
      { label: "Lost & Found" },
      { label: "Events" },
      { label: "Ride Sharing" },
      { label: "Group Activities" },
      { label: "Requests" },
      { label: "Polls" },
      { label: "Announcements" },
      { label: "Local News" },
      { label: "Emergency Alerts" },
    ],
  },
  events: {
    label: "Events",
    icon: Calendar01Icon,
    subcategories: [
      { label: "Sports" },
      { label: "Music" },
      { label: "Conferences" },
      { label: "Workshops" },
      { label: "Meetups" },
      { label: "Family" },
      { label: "Kids" },
      { label: "Festivals" },
      { label: "Charity" },
      { label: "Religious" },
    ],
  },
  government: {
    label: "Government",
    icon: BankIcon,
    subcategories: [
      { label: "Municipality" },
      { label: "Passport" },
      { label: "Traffic" },
      { label: "Taxes" },
      { label: "Courts" },
      { label: "Electricity" },
      { label: "Water" },
      { label: "Gas" },
      { label: "Internet" },
      { label: "Public Transport" },
    ],
  },
  emergency: {
    label: "Emergency",
    icon: Alert02Icon,
    subcategories: [
      { label: "Police" },
      { label: "Fire" },
      { label: "Ambulance" },
      { label: "Hospitals" },
      { label: "Pharmacies" },
      { label: "Road Assistance" },
      { label: "Emergency Plumbers" },
      { label: "Emergency Electricians" },
      { label: "SOS" },
    ],
  },
  lifestyle: {
    label: "Lifestyle",
    icon: FavouriteIcon,
    subcategories: [
      { label: "Pets" },
      { label: "Gyms" },
      { label: "Yoga" },
      { label: "Personal Trainers" },
      { label: "Clubs" },
      { label: "Entertainment" },
      { label: "Cinema" },
      { label: "Parks" },
      { label: "Kids Activities" },
      { label: "Hobbies" },
    ],
  },
};
